name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
          
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      - name: NuGet Restore
        if: steps.cache.outputs.cache-hit != 'true'
        run: nuget restore FlexDMD.sln
  
      - name: Build
        run: MSBuild.exe $Env:GITHUB_WORKSPACE/FlexDMD.sln /p:Configuration="ReleaseCI"

      - name: Package
        run: |
          mkdir tmp 
          cp FlexDMDUI\bin\ReleaseCI\FlexDMDUI.exe tmp
          cp FlexDMD\bin\ReleaseCI\ILMerge\FlexDMD.dll tmp
          cp FlexUDMD\bin\ReleaseCI\FlexUDMD.dll tmp
          cp FlexDMD.log.config tmp
          cp FlexDemo\FlexDemo.vpx tmp
          cp -r Scripts tmp/Scripts

      - uses: actions/upload-artifact@v2
        with: 
          name: FlexDMD
          path: tmp
